var hierarchy =
[
    [ "_SDLNet_GenericSocket", "struct__SDLNet__GenericSocket.html", null ],
    [ "AppProofOfPurchaseKeyResponse_t", "structAppProofOfPurchaseKeyResponse__t.html", null ],
    [ "Valve.Steamworks.AppProofOfPurchaseKeyResponse_t", "structValve_1_1Steamworks_1_1AppProofOfPurchaseKeyResponse__t.html", null ],
    [ "AssociateWithClanResult_t", "structAssociateWithClanResult__t.html", null ],
    [ "Valve.Steamworks.AssociateWithClanResult_t", "structValve_1_1Steamworks_1_1AssociateWithClanResult__t.html", null ],
    [ "Valve.Steamworks.AvatarImageLoaded_t", "structValve_1_1Steamworks_1_1AvatarImageLoaded__t.html", null ],
    [ "AvatarImageLoaded_t", "structAvatarImageLoaded__t.html", null ],
    [ "Valve.Steamworks.BroadcastUploadStop_t", "structValve_1_1Steamworks_1_1BroadcastUploadStop__t.html", null ],
    [ "Valve.Steamworks.CallbackMsg_t", "structValve_1_1Steamworks_1_1CallbackMsg__t.html", null ],
    [ "CallbackMsg_t", "structCallbackMsg__t.html", null ],
    [ "Valve.Steamworks.CCallback", "structValve_1_1Steamworks_1_1CCallback.html", null ],
    [ "CCallbackBase", "classCCallbackBase.html", [
      [ "CCallback< T, P, bGameServer >", "classCCallback.html", [
        [ "CCallbackManual< T, P, bGameServer >", "classCCallbackManual.html", null ]
      ] ],
      [ "CCallResult< T, P >", "classCCallResult.html", null ]
    ] ],
    [ "Valve.Steamworks.CCallbackBase", "structValve_1_1Steamworks_1_1CCallbackBase.html", null ],
    [ "Valve.Steamworks.CCallResult", "structValve_1_1Steamworks_1_1CCallResult.html", null ],
    [ "CGameID", "classCGameID.html", null ],
    [ "Valve.Steamworks.CheckFileSignature_t", "structValve_1_1Steamworks_1_1CheckFileSignature__t.html", null ],
    [ "CheckFileSignature_t", "structCheckFileSignature__t.html", null ],
    [ "Valve.Steamworks.ClanOfficerListResponse_t", "structValve_1_1Steamworks_1_1ClanOfficerListResponse__t.html", null ],
    [ "ClanOfficerListResponse_t", "structClanOfficerListResponse__t.html", null ],
    [ "Valve.Steamworks.ClientGameServerDeny_t", "structValve_1_1Steamworks_1_1ClientGameServerDeny__t.html", null ],
    [ "ClientGameServerDeny_t", "structClientGameServerDeny__t.html", null ],
    [ "ComputeNewPlayerCompatibilityResult_t", "structComputeNewPlayerCompatibilityResult__t.html", null ],
    [ "Valve.Steamworks.ComputeNewPlayerCompatibilityResult_t", "structValve_1_1Steamworks_1_1ComputeNewPlayerCompatibilityResult__t.html", null ],
    [ "CreateItemResult_t", "structCreateItemResult__t.html", null ],
    [ "Valve.Steamworks.CreateItemResult_t", "structValve_1_1Steamworks_1_1CreateItemResult__t.html", null ],
    [ "Valve.Steamworks.CSteamAPIContext", "structValve_1_1Steamworks_1_1CSteamAPIContext.html", null ],
    [ "Valve.Steamworks.CSteamID", "structValve_1_1Steamworks_1_1CSteamID.html", null ],
    [ "CSteamID", "classCSteamID.html", null ],
    [ "DlcInstalled_t", "structDlcInstalled__t.html", null ],
    [ "Valve.Steamworks.DlcInstalled_t", "structValve_1_1Steamworks_1_1DlcInstalled__t.html", null ],
    [ "Valve.Steamworks.DownloadClanActivityCountsResult_t", "structValve_1_1Steamworks_1_1DownloadClanActivityCountsResult__t.html", null ],
    [ "DownloadClanActivityCountsResult_t", "structDownloadClanActivityCountsResult__t.html", null ],
    [ "DownloadItemResult_t", "structDownloadItemResult__t.html", null ],
    [ "Valve.Steamworks.DownloadItemResult_t", "structValve_1_1Steamworks_1_1DownloadItemResult__t.html", null ],
    [ "Valve.Steamworks.EncryptedAppTicketResponse_t", "structValve_1_1Steamworks_1_1EncryptedAppTicketResponse__t.html", null ],
    [ "EncryptedAppTicketResponse_t", "structEncryptedAppTicketResponse__t.html", null ],
    [ "Engine", "classEngine.html", null ],
    [ "FavoritesListAccountsUpdated_t", "structFavoritesListAccountsUpdated__t.html", null ],
    [ "Valve.Steamworks.FavoritesListAccountsUpdated_t", "structValve_1_1Steamworks_1_1FavoritesListAccountsUpdated__t.html", null ],
    [ "FavoritesListChanged_t", "structFavoritesListChanged__t.html", null ],
    [ "Valve.Steamworks.FavoritesListChanged_t", "structValve_1_1Steamworks_1_1FavoritesListChanged__t.html", null ],
    [ "Valve.Steamworks.FriendGameInfo_t", "structValve_1_1Steamworks_1_1FriendGameInfo__t.html", null ],
    [ "FriendGameInfo_t", "structFriendGameInfo__t.html", null ],
    [ "Valve.Steamworks.FriendRichPresenceUpdate_t", "structValve_1_1Steamworks_1_1FriendRichPresenceUpdate__t.html", null ],
    [ "FriendRichPresenceUpdate_t", "structFriendRichPresenceUpdate__t.html", null ],
    [ "Valve.Steamworks.FriendsEnumerateFollowingList_t", "structValve_1_1Steamworks_1_1FriendsEnumerateFollowingList__t.html", null ],
    [ "FriendsEnumerateFollowingList_t", "structFriendsEnumerateFollowingList__t.html", null ],
    [ "Valve.Steamworks.FriendSessionStateInfo_t", "structValve_1_1Steamworks_1_1FriendSessionStateInfo__t.html", null ],
    [ "FriendSessionStateInfo_t", "structFriendSessionStateInfo__t.html", null ],
    [ "Valve.Steamworks.FriendsGetFollowerCount_t", "structValve_1_1Steamworks_1_1FriendsGetFollowerCount__t.html", null ],
    [ "FriendsGetFollowerCount_t", "structFriendsGetFollowerCount__t.html", null ],
    [ "Valve.Steamworks.FriendsIsFollowing_t", "structValve_1_1Steamworks_1_1FriendsIsFollowing__t.html", null ],
    [ "FriendsIsFollowing_t", "structFriendsIsFollowing__t.html", null ],
    [ "Valve.Steamworks.GameConnectedChatJoin_t", "structValve_1_1Steamworks_1_1GameConnectedChatJoin__t.html", null ],
    [ "GameConnectedChatJoin_t", "structGameConnectedChatJoin__t.html", null ],
    [ "Valve.Steamworks.GameConnectedChatLeave_t", "structValve_1_1Steamworks_1_1GameConnectedChatLeave__t.html", null ],
    [ "GameConnectedChatLeave_t", "structGameConnectedChatLeave__t.html", null ],
    [ "Valve.Steamworks.GameConnectedClanChatMsg_t", "structValve_1_1Steamworks_1_1GameConnectedClanChatMsg__t.html", null ],
    [ "GameConnectedClanChatMsg_t", "structGameConnectedClanChatMsg__t.html", null ],
    [ "Valve.Steamworks.GameConnectedFriendChatMsg_t", "structValve_1_1Steamworks_1_1GameConnectedFriendChatMsg__t.html", null ],
    [ "GameConnectedFriendChatMsg_t", "structGameConnectedFriendChatMsg__t.html", null ],
    [ "Valve.Steamworks.GameID_t", "structValve_1_1Steamworks_1_1GameID__t.html", null ],
    [ "Valve.Steamworks.GameLobbyJoinRequested_t", "structValve_1_1Steamworks_1_1GameLobbyJoinRequested__t.html", null ],
    [ "GameLobbyJoinRequested_t", "structGameLobbyJoinRequested__t.html", null ],
    [ "Valve.Steamworks.GameOverlayActivated_t", "structValve_1_1Steamworks_1_1GameOverlayActivated__t.html", null ],
    [ "GameOverlayActivated_t", "structGameOverlayActivated__t.html", null ],
    [ "Valve.Steamworks.GamepadTextInputDismissed_t", "structValve_1_1Steamworks_1_1GamepadTextInputDismissed__t.html", null ],
    [ "GamepadTextInputDismissed_t", "structGamepadTextInputDismissed__t.html", null ],
    [ "Valve.Steamworks.GameRichPresenceJoinRequested_t", "structValve_1_1Steamworks_1_1GameRichPresenceJoinRequested__t.html", null ],
    [ "GameRichPresenceJoinRequested_t", "structGameRichPresenceJoinRequested__t.html", null ],
    [ "Valve.Steamworks.GameServerChangeRequested_t", "structValve_1_1Steamworks_1_1GameServerChangeRequested__t.html", null ],
    [ "GameServerChangeRequested_t", "structGameServerChangeRequested__t.html", null ],
    [ "gameserveritem_t", "classgameserveritem__t.html", null ],
    [ "Valve.Steamworks.gameserveritem_t", "structValve_1_1Steamworks_1_1gameserveritem__t.html", null ],
    [ "Valve.Steamworks.GameWebCallback_t", "structValve_1_1Steamworks_1_1GameWebCallback__t.html", null ],
    [ "GameWebCallback_t", "structGameWebCallback__t.html", null ],
    [ "GCMessageAvailable_t", "structGCMessageAvailable__t.html", null ],
    [ "GCMessageFailed_t", "structGCMessageFailed__t.html", null ],
    [ "Valve.Steamworks.GetAuthSessionTicketResponse_t", "structValve_1_1Steamworks_1_1GetAuthSessionTicketResponse__t.html", null ],
    [ "GetAuthSessionTicketResponse_t", "structGetAuthSessionTicketResponse__t.html", null ],
    [ "GetUserItemVoteResult_t", "structGetUserItemVoteResult__t.html", null ],
    [ "Valve.Steamworks.GetUserItemVoteResult_t", "structValve_1_1Steamworks_1_1GetUserItemVoteResult__t.html", null ],
    [ "Valve.Steamworks.GetVideoURLResult_t", "structValve_1_1Steamworks_1_1GetVideoURLResult__t.html", null ],
    [ "Valve.Steamworks.GlobalAchievementPercentagesReady_t", "structValve_1_1Steamworks_1_1GlobalAchievementPercentagesReady__t.html", null ],
    [ "GlobalAchievementPercentagesReady_t", "structGlobalAchievementPercentagesReady__t.html", null ],
    [ "Valve.Steamworks.GlobalStatsReceived_t", "structValve_1_1Steamworks_1_1GlobalStatsReceived__t.html", null ],
    [ "GlobalStatsReceived_t", "structGlobalStatsReceived__t.html", null ],
    [ "Valve.Steamworks.GSClientAchievementStatus_t", "structValve_1_1Steamworks_1_1GSClientAchievementStatus__t.html", null ],
    [ "GSClientAchievementStatus_t", "structGSClientAchievementStatus__t.html", null ],
    [ "Valve.Steamworks.GSClientApprove_t", "structValve_1_1Steamworks_1_1GSClientApprove__t.html", null ],
    [ "GSClientApprove_t", "structGSClientApprove__t.html", null ],
    [ "Valve.Steamworks.GSClientDeny_t", "structValve_1_1Steamworks_1_1GSClientDeny__t.html", null ],
    [ "GSClientDeny_t", "structGSClientDeny__t.html", null ],
    [ "GSClientGroupStatus_t", "structGSClientGroupStatus__t.html", null ],
    [ "Valve.Steamworks.GSClientGroupStatus_t", "structValve_1_1Steamworks_1_1GSClientGroupStatus__t.html", null ],
    [ "Valve.Steamworks.GSClientKick_t", "structValve_1_1Steamworks_1_1GSClientKick__t.html", null ],
    [ "GSClientKick_t", "structGSClientKick__t.html", null ],
    [ "Valve.Steamworks.GSGameplayStats_t", "structValve_1_1Steamworks_1_1GSGameplayStats__t.html", null ],
    [ "GSGameplayStats_t", "structGSGameplayStats__t.html", null ],
    [ "Valve.Steamworks.GSPolicyResponse_t", "structValve_1_1Steamworks_1_1GSPolicyResponse__t.html", null ],
    [ "GSPolicyResponse_t", "structGSPolicyResponse__t.html", null ],
    [ "GSReputation_t", "structGSReputation__t.html", null ],
    [ "Valve.Steamworks.GSReputation_t", "structValve_1_1Steamworks_1_1GSReputation__t.html", null ],
    [ "GSStatsReceived_t", "structGSStatsReceived__t.html", null ],
    [ "Valve.Steamworks.GSStatsReceived_t", "structValve_1_1Steamworks_1_1GSStatsReceived__t.html", null ],
    [ "GSStatsStored_t", "structGSStatsStored__t.html", null ],
    [ "Valve.Steamworks.GSStatsStored_t", "structValve_1_1Steamworks_1_1GSStatsStored__t.html", null ],
    [ "GSStatsUnloaded_t", "structGSStatsUnloaded__t.html", null ],
    [ "Valve.Steamworks.GSStatsUnloaded_t", "structValve_1_1Steamworks_1_1GSStatsUnloaded__t.html", null ],
    [ "Valve.Steamworks.HTML_BrowserReady_t", "structValve_1_1Steamworks_1_1HTML__BrowserReady__t.html", null ],
    [ "Valve.Steamworks.HTML_CanGoBackAndForward_t", "structValve_1_1Steamworks_1_1HTML__CanGoBackAndForward__t.html", null ],
    [ "Valve.Steamworks.HTML_ChangedTitle_t", "structValve_1_1Steamworks_1_1HTML__ChangedTitle__t.html", null ],
    [ "Valve.Steamworks.HTML_CloseBrowser_t", "structValve_1_1Steamworks_1_1HTML__CloseBrowser__t.html", null ],
    [ "Valve.Steamworks.HTML_FileOpenDialog_t", "structValve_1_1Steamworks_1_1HTML__FileOpenDialog__t.html", null ],
    [ "Valve.Steamworks.HTML_FinishedRequest_t", "structValve_1_1Steamworks_1_1HTML__FinishedRequest__t.html", null ],
    [ "Valve.Steamworks.HTML_HideToolTip_t", "structValve_1_1Steamworks_1_1HTML__HideToolTip__t.html", null ],
    [ "Valve.Steamworks.HTML_HorizontalScroll_t", "structValve_1_1Steamworks_1_1HTML__HorizontalScroll__t.html", null ],
    [ "Valve.Steamworks.HTML_JSAlert_t", "structValve_1_1Steamworks_1_1HTML__JSAlert__t.html", null ],
    [ "Valve.Steamworks.HTML_JSConfirm_t", "structValve_1_1Steamworks_1_1HTML__JSConfirm__t.html", null ],
    [ "Valve.Steamworks.HTML_LinkAtPosition_t", "structValve_1_1Steamworks_1_1HTML__LinkAtPosition__t.html", null ],
    [ "Valve.Steamworks.HTML_NeedsPaint_t", "structValve_1_1Steamworks_1_1HTML__NeedsPaint__t.html", null ],
    [ "Valve.Steamworks.HTML_NewWindow_t", "structValve_1_1Steamworks_1_1HTML__NewWindow__t.html", null ],
    [ "Valve.Steamworks.HTML_OpenLinkInNewTab_t", "structValve_1_1Steamworks_1_1HTML__OpenLinkInNewTab__t.html", null ],
    [ "Valve.Steamworks.HTML_SearchResults_t", "structValve_1_1Steamworks_1_1HTML__SearchResults__t.html", null ],
    [ "Valve.Steamworks.HTML_SetCursor_t", "structValve_1_1Steamworks_1_1HTML__SetCursor__t.html", null ],
    [ "Valve.Steamworks.HTML_ShowToolTip_t", "structValve_1_1Steamworks_1_1HTML__ShowToolTip__t.html", null ],
    [ "Valve.Steamworks.HTML_StartRequest_t", "structValve_1_1Steamworks_1_1HTML__StartRequest__t.html", null ],
    [ "Valve.Steamworks.HTML_StatusText_t", "structValve_1_1Steamworks_1_1HTML__StatusText__t.html", null ],
    [ "Valve.Steamworks.HTML_UpdateToolTip_t", "structValve_1_1Steamworks_1_1HTML__UpdateToolTip__t.html", null ],
    [ "Valve.Steamworks.HTML_URLChanged_t", "structValve_1_1Steamworks_1_1HTML__URLChanged__t.html", null ],
    [ "Valve.Steamworks.HTML_VerticalScroll_t", "structValve_1_1Steamworks_1_1HTML__VerticalScroll__t.html", null ],
    [ "HTTPRequestCompleted_t", "structHTTPRequestCompleted__t.html", null ],
    [ "Valve.Steamworks.HTTPRequestCompleted_t", "structValve_1_1Steamworks_1_1HTTPRequestCompleted__t.html", null ],
    [ "HTTPRequestDataReceived_t", "structHTTPRequestDataReceived__t.html", null ],
    [ "Valve.Steamworks.HTTPRequestDataReceived_t", "structValve_1_1Steamworks_1_1HTTPRequestDataReceived__t.html", null ],
    [ "HTTPRequestHeadersReceived_t", "structHTTPRequestHeadersReceived__t.html", null ],
    [ "Valve.Steamworks.HTTPRequestHeadersReceived_t", "structValve_1_1Steamworks_1_1HTTPRequestHeadersReceived__t.html", null ],
    [ "IPaddress", "structIPaddress.html", null ],
    [ "IPCFailure_t", "structIPCFailure__t.html", null ],
    [ "IPCountry_t", "structIPCountry__t.html", null ],
    [ "Valve.Steamworks.ISteamAppList", "classValve_1_1Steamworks_1_1ISteamAppList.html", [
      [ "Valve.Steamworks.CSteamAppList", "classValve_1_1Steamworks_1_1CSteamAppList.html", null ]
    ] ],
    [ "ISteamAppList", "classISteamAppList.html", null ],
    [ "Valve.Steamworks.ISteamApps", "classValve_1_1Steamworks_1_1ISteamApps.html", [
      [ "Valve.Steamworks.CSteamApps", "classValve_1_1Steamworks_1_1CSteamApps.html", null ]
    ] ],
    [ "ISteamApps", "classISteamApps.html", null ],
    [ "ISteamAppTicket", "classISteamAppTicket.html", null ],
    [ "Valve.Steamworks.ISteamClient", "classValve_1_1Steamworks_1_1ISteamClient.html", [
      [ "Valve.Steamworks.CSteamClient", "classValve_1_1Steamworks_1_1CSteamClient.html", null ]
    ] ],
    [ "ISteamClient", "classISteamClient.html", null ],
    [ "Valve.Steamworks.ISteamController", "classValve_1_1Steamworks_1_1ISteamController.html", [
      [ "Valve.Steamworks.CSteamController", "classValve_1_1Steamworks_1_1CSteamController.html", null ]
    ] ],
    [ "ISteamController", "classISteamController.html", null ],
    [ "Valve.Steamworks.ISteamFriends", "classValve_1_1Steamworks_1_1ISteamFriends.html", [
      [ "Valve.Steamworks.CSteamFriends", "classValve_1_1Steamworks_1_1CSteamFriends.html", null ]
    ] ],
    [ "ISteamFriends", "classISteamFriends.html", null ],
    [ "ISteamGameCoordinator", "classISteamGameCoordinator.html", null ],
    [ "Valve.Steamworks.ISteamGameServer", "classValve_1_1Steamworks_1_1ISteamGameServer.html", [
      [ "Valve.Steamworks.CSteamGameServer", "classValve_1_1Steamworks_1_1CSteamGameServer.html", null ]
    ] ],
    [ "ISteamGameServer", "classISteamGameServer.html", null ],
    [ "ISteamGameServerStats", "classISteamGameServerStats.html", null ],
    [ "Valve.Steamworks.ISteamGameServerStats", "classValve_1_1Steamworks_1_1ISteamGameServerStats.html", [
      [ "Valve.Steamworks.CSteamGameServerStats", "classValve_1_1Steamworks_1_1CSteamGameServerStats.html", null ]
    ] ],
    [ "ISteamHTMLSurface", "classISteamHTMLSurface.html", null ],
    [ "Valve.Steamworks.ISteamHTMLSurface", "classValve_1_1Steamworks_1_1ISteamHTMLSurface.html", [
      [ "Valve.Steamworks.CSteamHTMLSurface", "classValve_1_1Steamworks_1_1CSteamHTMLSurface.html", null ]
    ] ],
    [ "ISteamHTTP", "classISteamHTTP.html", null ],
    [ "Valve.Steamworks.ISteamHTTP", "classValve_1_1Steamworks_1_1ISteamHTTP.html", [
      [ "Valve.Steamworks.CSteamHTTP", "classValve_1_1Steamworks_1_1CSteamHTTP.html", null ]
    ] ],
    [ "ISteamInventory", "classISteamInventory.html", null ],
    [ "Valve.Steamworks.ISteamInventory", "classValve_1_1Steamworks_1_1ISteamInventory.html", [
      [ "Valve.Steamworks.CSteamInventory", "classValve_1_1Steamworks_1_1CSteamInventory.html", null ]
    ] ],
    [ "Valve.Steamworks.ISteamMatchmaking", "classValve_1_1Steamworks_1_1ISteamMatchmaking.html", [
      [ "Valve.Steamworks.CSteamMatchmaking", "classValve_1_1Steamworks_1_1CSteamMatchmaking.html", null ]
    ] ],
    [ "ISteamMatchmaking", "classISteamMatchmaking.html", null ],
    [ "Valve.Steamworks.ISteamMatchmakingPingResponse", "classValve_1_1Steamworks_1_1ISteamMatchmakingPingResponse.html", [
      [ "Valve.Steamworks.CSteamMatchmakingPingResponse", "classValve_1_1Steamworks_1_1CSteamMatchmakingPingResponse.html", null ]
    ] ],
    [ "ISteamMatchmakingPingResponse", "classISteamMatchmakingPingResponse.html", null ],
    [ "Valve.Steamworks.ISteamMatchmakingPlayersResponse", "classValve_1_1Steamworks_1_1ISteamMatchmakingPlayersResponse.html", [
      [ "Valve.Steamworks.CSteamMatchmakingPlayersResponse", "classValve_1_1Steamworks_1_1CSteamMatchmakingPlayersResponse.html", null ]
    ] ],
    [ "ISteamMatchmakingPlayersResponse", "classISteamMatchmakingPlayersResponse.html", null ],
    [ "Valve.Steamworks.ISteamMatchmakingRulesResponse", "classValve_1_1Steamworks_1_1ISteamMatchmakingRulesResponse.html", [
      [ "Valve.Steamworks.CSteamMatchmakingRulesResponse", "classValve_1_1Steamworks_1_1CSteamMatchmakingRulesResponse.html", null ]
    ] ],
    [ "ISteamMatchmakingRulesResponse", "classISteamMatchmakingRulesResponse.html", null ],
    [ "Valve.Steamworks.ISteamMatchmakingServerListResponse", "classValve_1_1Steamworks_1_1ISteamMatchmakingServerListResponse.html", [
      [ "Valve.Steamworks.CSteamMatchmakingServerListResponse", "classValve_1_1Steamworks_1_1CSteamMatchmakingServerListResponse.html", null ]
    ] ],
    [ "ISteamMatchmakingServerListResponse", "classISteamMatchmakingServerListResponse.html", null ],
    [ "Valve.Steamworks.ISteamMatchmakingServers", "classValve_1_1Steamworks_1_1ISteamMatchmakingServers.html", [
      [ "Valve.Steamworks.CSteamMatchmakingServers", "classValve_1_1Steamworks_1_1CSteamMatchmakingServers.html", null ]
    ] ],
    [ "ISteamMatchmakingServers", "classISteamMatchmakingServers.html", null ],
    [ "Valve.Steamworks.ISteamMusic", "classValve_1_1Steamworks_1_1ISteamMusic.html", [
      [ "Valve.Steamworks.CSteamMusic", "classValve_1_1Steamworks_1_1CSteamMusic.html", null ]
    ] ],
    [ "ISteamMusic", "classISteamMusic.html", null ],
    [ "Valve.Steamworks.ISteamMusicRemote", "classValve_1_1Steamworks_1_1ISteamMusicRemote.html", [
      [ "Valve.Steamworks.CSteamMusicRemote", "classValve_1_1Steamworks_1_1CSteamMusicRemote.html", null ]
    ] ],
    [ "ISteamMusicRemote", "classISteamMusicRemote.html", null ],
    [ "Valve.Steamworks.ISteamNetworking", "classValve_1_1Steamworks_1_1ISteamNetworking.html", [
      [ "Valve.Steamworks.CSteamNetworking", "classValve_1_1Steamworks_1_1CSteamNetworking.html", null ]
    ] ],
    [ "ISteamNetworking", "classISteamNetworking.html", null ],
    [ "ISteamPS3OverlayRender", "classISteamPS3OverlayRender.html", null ],
    [ "ISteamPS3OverlayRenderHost", "classISteamPS3OverlayRenderHost.html", null ],
    [ "Valve.Steamworks.ISteamRemoteStorage", "classValve_1_1Steamworks_1_1ISteamRemoteStorage.html", [
      [ "Valve.Steamworks.CSteamRemoteStorage", "classValve_1_1Steamworks_1_1CSteamRemoteStorage.html", null ]
    ] ],
    [ "ISteamRemoteStorage", "classISteamRemoteStorage.html", null ],
    [ "Valve.Steamworks.ISteamScreenshots", "classValve_1_1Steamworks_1_1ISteamScreenshots.html", [
      [ "Valve.Steamworks.CSteamScreenshots", "classValve_1_1Steamworks_1_1CSteamScreenshots.html", null ]
    ] ],
    [ "ISteamScreenshots", "classISteamScreenshots.html", null ],
    [ "Valve.Steamworks.ISteamUGC", "classValve_1_1Steamworks_1_1ISteamUGC.html", [
      [ "Valve.Steamworks.CSteamUGC", "classValve_1_1Steamworks_1_1CSteamUGC.html", null ]
    ] ],
    [ "ISteamUGC", "classISteamUGC.html", null ],
    [ "Valve.Steamworks.ISteamUnifiedMessages", "classValve_1_1Steamworks_1_1ISteamUnifiedMessages.html", [
      [ "Valve.Steamworks.CSteamUnifiedMessages", "classValve_1_1Steamworks_1_1CSteamUnifiedMessages.html", null ]
    ] ],
    [ "ISteamUnifiedMessages", "classISteamUnifiedMessages.html", null ],
    [ "Valve.Steamworks.ISteamUser", "classValve_1_1Steamworks_1_1ISteamUser.html", [
      [ "Valve.Steamworks.CSteamUser", "classValve_1_1Steamworks_1_1CSteamUser.html", null ]
    ] ],
    [ "ISteamUser", "classISteamUser.html", null ],
    [ "Valve.Steamworks.ISteamUserStats", "classValve_1_1Steamworks_1_1ISteamUserStats.html", [
      [ "Valve.Steamworks.CSteamUserStats", "classValve_1_1Steamworks_1_1CSteamUserStats.html", null ]
    ] ],
    [ "ISteamUserStats", "classISteamUserStats.html", null ],
    [ "Valve.Steamworks.ISteamUtils", "classValve_1_1Steamworks_1_1ISteamUtils.html", [
      [ "Valve.Steamworks.CSteamUtils", "classValve_1_1Steamworks_1_1CSteamUtils.html", null ]
    ] ],
    [ "ISteamUtils", "classISteamUtils.html", null ],
    [ "Valve.Steamworks.ISteamVideo", "classValve_1_1Steamworks_1_1ISteamVideo.html", [
      [ "Valve.Steamworks.CSteamVideo", "classValve_1_1Steamworks_1_1CSteamVideo.html", null ]
    ] ],
    [ "ISteamVideo", "classISteamVideo.html", null ],
    [ "ItemInstalled_t", "structItemInstalled__t.html", null ],
    [ "JoinClanChatRoomCompletionResult_t", "structJoinClanChatRoomCompletionResult__t.html", null ],
    [ "Valve.Steamworks.JoinClanChatRoomCompletionResult_t", "structValve_1_1Steamworks_1_1JoinClanChatRoomCompletionResult__t.html", null ],
    [ "Valve.Steamworks.LeaderboardEntry_t", "structValve_1_1Steamworks_1_1LeaderboardEntry__t.html", null ],
    [ "LeaderboardEntry_t", "structLeaderboardEntry__t.html", null ],
    [ "Valve.Steamworks.LeaderboardFindResult_t", "structValve_1_1Steamworks_1_1LeaderboardFindResult__t.html", null ],
    [ "LeaderboardFindResult_t", "structLeaderboardFindResult__t.html", null ],
    [ "Valve.Steamworks.LeaderboardScoresDownloaded_t", "structValve_1_1Steamworks_1_1LeaderboardScoresDownloaded__t.html", null ],
    [ "LeaderboardScoresDownloaded_t", "structLeaderboardScoresDownloaded__t.html", null ],
    [ "LeaderboardScoreUploaded_t", "structLeaderboardScoreUploaded__t.html", null ],
    [ "Valve.Steamworks.LeaderboardScoreUploaded_t", "structValve_1_1Steamworks_1_1LeaderboardScoreUploaded__t.html", null ],
    [ "Valve.Steamworks.LeaderboardUGCSet_t", "structValve_1_1Steamworks_1_1LeaderboardUGCSet__t.html", null ],
    [ "LeaderboardUGCSet_t", "structLeaderboardUGCSet__t.html", null ],
    [ "LicensesUpdated_t", "structLicensesUpdated__t.html", null ],
    [ "LobbyChatMsg_t", "structLobbyChatMsg__t.html", null ],
    [ "Valve.Steamworks.LobbyChatMsg_t", "structValve_1_1Steamworks_1_1LobbyChatMsg__t.html", null ],
    [ "LobbyChatUpdate_t", "structLobbyChatUpdate__t.html", null ],
    [ "Valve.Steamworks.LobbyChatUpdate_t", "structValve_1_1Steamworks_1_1LobbyChatUpdate__t.html", null ],
    [ "LobbyCreated_t", "structLobbyCreated__t.html", null ],
    [ "Valve.Steamworks.LobbyCreated_t", "structValve_1_1Steamworks_1_1LobbyCreated__t.html", null ],
    [ "LobbyDataUpdate_t", "structLobbyDataUpdate__t.html", null ],
    [ "Valve.Steamworks.LobbyDataUpdate_t", "structValve_1_1Steamworks_1_1LobbyDataUpdate__t.html", null ],
    [ "LobbyEnter_t", "structLobbyEnter__t.html", null ],
    [ "Valve.Steamworks.LobbyEnter_t", "structValve_1_1Steamworks_1_1LobbyEnter__t.html", null ],
    [ "LobbyGameCreated_t", "structLobbyGameCreated__t.html", null ],
    [ "Valve.Steamworks.LobbyGameCreated_t", "structValve_1_1Steamworks_1_1LobbyGameCreated__t.html", null ],
    [ "LobbyInvite_t", "structLobbyInvite__t.html", null ],
    [ "Valve.Steamworks.LobbyInvite_t", "structValve_1_1Steamworks_1_1LobbyInvite__t.html", null ],
    [ "LobbyKicked_t", "structLobbyKicked__t.html", null ],
    [ "Valve.Steamworks.LobbyKicked_t", "structValve_1_1Steamworks_1_1LobbyKicked__t.html", null ],
    [ "LobbyMatchList_t", "structLobbyMatchList__t.html", null ],
    [ "Valve.Steamworks.LobbyMatchList_t", "structValve_1_1Steamworks_1_1LobbyMatchList__t.html", null ],
    [ "Valve.Steamworks.LowBatteryPower_t", "structValve_1_1Steamworks_1_1LowBatteryPower__t.html", null ],
    [ "LowBatteryPower_t", "structLowBatteryPower__t.html", null ],
    [ "lua_Debug", "structlua__Debug.html", null ],
    [ "luaL_Buffer", "structluaL__Buffer.html", null ],
    [ "luaL_Reg", "structluaL__Reg.html", null ],
    [ "luaL_Stream", "structluaL__Stream.html", null ],
    [ "Valve.Steamworks.MatchMakingKeyValuePair_t", "structValve_1_1Steamworks_1_1MatchMakingKeyValuePair__t.html", null ],
    [ "MatchMakingKeyValuePair_t", "structMatchMakingKeyValuePair__t.html", null ],
    [ "Valve.Steamworks.MicroTxnAuthorizationResponse_t", "structValve_1_1Steamworks_1_1MicroTxnAuthorizationResponse__t.html", null ],
    [ "MicroTxnAuthorizationResponse_t", "structMicroTxnAuthorizationResponse__t.html", null ],
    [ "Mix_Chunk", "structMix__Chunk.html", null ],
    [ "Valve.Steamworks.MusicPlayerSelectsPlaylistEntry_t", "structValve_1_1Steamworks_1_1MusicPlayerSelectsPlaylistEntry__t.html", null ],
    [ "Valve.Steamworks.MusicPlayerSelectsQueueEntry_t", "structValve_1_1Steamworks_1_1MusicPlayerSelectsQueueEntry__t.html", null ],
    [ "Valve.Steamworks.MusicPlayerWantsLooped_t", "structValve_1_1Steamworks_1_1MusicPlayerWantsLooped__t.html", null ],
    [ "Valve.Steamworks.MusicPlayerWantsPlayingRepeatStatus_t", "structValve_1_1Steamworks_1_1MusicPlayerWantsPlayingRepeatStatus__t.html", null ],
    [ "Valve.Steamworks.MusicPlayerWantsShuffled_t", "structValve_1_1Steamworks_1_1MusicPlayerWantsShuffled__t.html", null ],
    [ "Valve.Steamworks.MusicPlayerWantsVolume_t", "structValve_1_1Steamworks_1_1MusicPlayerWantsVolume__t.html", null ],
    [ "Valve.Interop.NativeEntrypoints", "classValve_1_1Interop_1_1NativeEntrypoints.html", null ],
    [ "NewLaunchQueryParameters_t", "structNewLaunchQueryParameters__t.html", null ],
    [ "Valve.Steamworks.NumberOfCurrentPlayers_t", "structValve_1_1Steamworks_1_1NumberOfCurrentPlayers__t.html", null ],
    [ "NumberOfCurrentPlayers_t", "structNumberOfCurrentPlayers__t.html", null ],
    [ "P2PSessionConnectFail_t", "structP2PSessionConnectFail__t.html", null ],
    [ "Valve.Steamworks.P2PSessionConnectFail_t", "structValve_1_1Steamworks_1_1P2PSessionConnectFail__t.html", null ],
    [ "P2PSessionRequest_t", "structP2PSessionRequest__t.html", null ],
    [ "Valve.Steamworks.P2PSessionRequest_t", "structValve_1_1Steamworks_1_1P2PSessionRequest__t.html", null ],
    [ "P2PSessionState_t", "structP2PSessionState__t.html", null ],
    [ "Valve.Steamworks.P2PSessionState_t", "structValve_1_1Steamworks_1_1P2PSessionState__t.html", null ],
    [ "Valve.Steamworks.PersonaStateChange_t", "structValve_1_1Steamworks_1_1PersonaStateChange__t.html", null ],
    [ "PersonaStateChange_t", "structPersonaStateChange__t.html", null ],
    [ "SteamPS3Params_t::Ps3jpgInit_t", "structSteamPS3Params__t_1_1Ps3jpgInit__t.html", null ],
    [ "SteamPS3Params_t::Ps3netInit_t", "structSteamPS3Params__t_1_1Ps3netInit__t.html", null ],
    [ "SteamPS3Params_t::Ps3pngInit_t", "structSteamPS3Params__t_1_1Ps3pngInit__t.html", null ],
    [ "SteamPS3Params_t::Ps3sysutilUserInfo_t", "structSteamPS3Params__t_1_1Ps3sysutilUserInfo__t.html", null ],
    [ "Valve.Steamworks.PS3TrophiesInstalled_t", "structValve_1_1Steamworks_1_1PS3TrophiesInstalled__t.html", null ],
    [ "PS3TrophiesInstalled_t", "structPS3TrophiesInstalled__t.html", null ],
    [ "PSNGameBootInviteResult_t", "structPSNGameBootInviteResult__t.html", null ],
    [ "Valve.Steamworks.PSNGameBootInviteResult_t", "structValve_1_1Steamworks_1_1PSNGameBootInviteResult__t.html", null ],
    [ "RegisterActivationCodeResponse_t", "structRegisterActivationCodeResponse__t.html", null ],
    [ "Valve.Steamworks.RegisterActivationCodeResponse_t", "structValve_1_1Steamworks_1_1RegisterActivationCodeResponse__t.html", null ],
    [ "RemoteStorageAppSyncedClient_t", "structRemoteStorageAppSyncedClient__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageAppSyncedClient_t", "structValve_1_1Steamworks_1_1RemoteStorageAppSyncedClient__t.html", null ],
    [ "RemoteStorageAppSyncedServer_t", "structRemoteStorageAppSyncedServer__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageAppSyncedServer_t", "structValve_1_1Steamworks_1_1RemoteStorageAppSyncedServer__t.html", null ],
    [ "RemoteStorageAppSyncProgress_t", "structRemoteStorageAppSyncProgress__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageAppSyncProgress_t", "structValve_1_1Steamworks_1_1RemoteStorageAppSyncProgress__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageAppSyncStatusCheck_t", "structValve_1_1Steamworks_1_1RemoteStorageAppSyncStatusCheck__t.html", null ],
    [ "RemoteStorageAppSyncStatusCheck_t", "structRemoteStorageAppSyncStatusCheck__t.html", null ],
    [ "RemoteStorageConflictResolution_t", "structRemoteStorageConflictResolution__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageConflictResolution_t", "structValve_1_1Steamworks_1_1RemoteStorageConflictResolution__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageDeletePublishedFileResult_t", "structValve_1_1Steamworks_1_1RemoteStorageDeletePublishedFileResult__t.html", null ],
    [ "RemoteStorageDeletePublishedFileResult_t", "structRemoteStorageDeletePublishedFileResult__t.html", null ],
    [ "RemoteStorageDownloadUGCResult_t", "structRemoteStorageDownloadUGCResult__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageDownloadUGCResult_t", "structValve_1_1Steamworks_1_1RemoteStorageDownloadUGCResult__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageEnumeratePublishedFilesByUserActionResult_t", "structValve_1_1Steamworks_1_1RemoteStorageEnumeratePublishedFilesByUserActionResult__t.html", null ],
    [ "RemoteStorageEnumeratePublishedFilesByUserActionResult_t", "structRemoteStorageEnumeratePublishedFilesByUserActionResult__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageEnumerateUserPublishedFilesResult_t", "structValve_1_1Steamworks_1_1RemoteStorageEnumerateUserPublishedFilesResult__t.html", null ],
    [ "RemoteStorageEnumerateUserPublishedFilesResult_t", "structRemoteStorageEnumerateUserPublishedFilesResult__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageEnumerateUserSharedWorkshopFilesResult_t", "structValve_1_1Steamworks_1_1RemoteStorageEnumerateUserSharedWorkshopFilesResult__t.html", null ],
    [ "RemoteStorageEnumerateUserSharedWorkshopFilesResult_t", "structRemoteStorageEnumerateUserSharedWorkshopFilesResult__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageEnumerateUserSubscribedFilesResult_t", "structValve_1_1Steamworks_1_1RemoteStorageEnumerateUserSubscribedFilesResult__t.html", null ],
    [ "RemoteStorageEnumerateUserSubscribedFilesResult_t", "structRemoteStorageEnumerateUserSubscribedFilesResult__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageEnumerateWorkshopFilesResult_t", "structValve_1_1Steamworks_1_1RemoteStorageEnumerateWorkshopFilesResult__t.html", null ],
    [ "RemoteStorageEnumerateWorkshopFilesResult_t", "structRemoteStorageEnumerateWorkshopFilesResult__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageFileShareResult_t", "structValve_1_1Steamworks_1_1RemoteStorageFileShareResult__t.html", null ],
    [ "RemoteStorageFileShareResult_t", "structRemoteStorageFileShareResult__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageGetPublishedFileDetailsResult_t", "structValve_1_1Steamworks_1_1RemoteStorageGetPublishedFileDetailsResult__t.html", null ],
    [ "RemoteStorageGetPublishedFileDetailsResult_t", "structRemoteStorageGetPublishedFileDetailsResult__t.html", null ],
    [ "RemoteStorageGetPublishedItemVoteDetailsResult_t", "structRemoteStorageGetPublishedItemVoteDetailsResult__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageGetPublishedItemVoteDetailsResult_t", "structValve_1_1Steamworks_1_1RemoteStorageGetPublishedItemVoteDetailsResult__t.html", null ],
    [ "Valve.Steamworks.RemoteStoragePublishedFileDeleted_t", "structValve_1_1Steamworks_1_1RemoteStoragePublishedFileDeleted__t.html", null ],
    [ "RemoteStoragePublishedFileDeleted_t", "structRemoteStoragePublishedFileDeleted__t.html", null ],
    [ "Valve.Steamworks.RemoteStoragePublishedFileSubscribed_t", "structValve_1_1Steamworks_1_1RemoteStoragePublishedFileSubscribed__t.html", null ],
    [ "RemoteStoragePublishedFileSubscribed_t", "structRemoteStoragePublishedFileSubscribed__t.html", null ],
    [ "Valve.Steamworks.RemoteStoragePublishedFileUnsubscribed_t", "structValve_1_1Steamworks_1_1RemoteStoragePublishedFileUnsubscribed__t.html", null ],
    [ "RemoteStoragePublishedFileUnsubscribed_t", "structRemoteStoragePublishedFileUnsubscribed__t.html", null ],
    [ "RemoteStoragePublishedFileUpdated_t", "structRemoteStoragePublishedFileUpdated__t.html", null ],
    [ "Valve.Steamworks.RemoteStoragePublishedFileUpdated_t", "structValve_1_1Steamworks_1_1RemoteStoragePublishedFileUpdated__t.html", null ],
    [ "RemoteStoragePublishFileProgress_t", "structRemoteStoragePublishFileProgress__t.html", null ],
    [ "Valve.Steamworks.RemoteStoragePublishFileProgress_t", "structValve_1_1Steamworks_1_1RemoteStoragePublishFileProgress__t.html", null ],
    [ "Valve.Steamworks.RemoteStoragePublishFileResult_t", "structValve_1_1Steamworks_1_1RemoteStoragePublishFileResult__t.html", null ],
    [ "RemoteStoragePublishFileResult_t", "structRemoteStoragePublishFileResult__t.html", null ],
    [ "RemoteStorageSetUserPublishedFileActionResult_t", "structRemoteStorageSetUserPublishedFileActionResult__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageSetUserPublishedFileActionResult_t", "structValve_1_1Steamworks_1_1RemoteStorageSetUserPublishedFileActionResult__t.html", null ],
    [ "RemoteStorageSubscribePublishedFileResult_t", "structRemoteStorageSubscribePublishedFileResult__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageSubscribePublishedFileResult_t", "structValve_1_1Steamworks_1_1RemoteStorageSubscribePublishedFileResult__t.html", null ],
    [ "RemoteStorageUnsubscribePublishedFileResult_t", "structRemoteStorageUnsubscribePublishedFileResult__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageUnsubscribePublishedFileResult_t", "structValve_1_1Steamworks_1_1RemoteStorageUnsubscribePublishedFileResult__t.html", null ],
    [ "RemoteStorageUpdatePublishedFileResult_t", "structRemoteStorageUpdatePublishedFileResult__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageUpdatePublishedFileResult_t", "structValve_1_1Steamworks_1_1RemoteStorageUpdatePublishedFileResult__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageUpdateUserPublishedItemVoteResult_t", "structValve_1_1Steamworks_1_1RemoteStorageUpdateUserPublishedItemVoteResult__t.html", null ],
    [ "RemoteStorageUpdateUserPublishedItemVoteResult_t", "structRemoteStorageUpdateUserPublishedItemVoteResult__t.html", null ],
    [ "RemoteStorageUserVoteDetails_t", "structRemoteStorageUserVoteDetails__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageUserVoteDetails_t", "structValve_1_1Steamworks_1_1RemoteStorageUserVoteDetails__t.html", null ],
    [ "ScreenshotReady_t", "structScreenshotReady__t.html", null ],
    [ "Valve.Steamworks.ScreenshotReady_t", "structValve_1_1Steamworks_1_1ScreenshotReady__t.html", null ],
    [ "ScreenshotRequested_t", "structScreenshotRequested__t.html", null ],
    [ "SDL_assert_data", "structSDL__assert__data.html", null ],
    [ "SDL_atomic_t", "structSDL__atomic__t.html", null ],
    [ "SDL_AudioCVT", "structSDL__AudioCVT.html", null ],
    [ "SDL_AudioSpec", "structSDL__AudioSpec.html", null ],
    [ "SDL_Color", "structSDL__Color.html", null ],
    [ "SDL_CommonEvent", "structSDL__CommonEvent.html", null ],
    [ "SDL_ControllerAxisEvent", "structSDL__ControllerAxisEvent.html", null ],
    [ "SDL_ControllerButtonEvent", "structSDL__ControllerButtonEvent.html", null ],
    [ "SDL_ControllerDeviceEvent", "structSDL__ControllerDeviceEvent.html", null ],
    [ "SDL_DisplayMode", "structSDL__DisplayMode.html", null ],
    [ "SDL_DollarGestureEvent", "structSDL__DollarGestureEvent.html", null ],
    [ "SDL_DropEvent", "structSDL__DropEvent.html", null ],
    [ "SDL_Event", "unionSDL__Event.html", null ],
    [ "SDL_Finger", "structSDL__Finger.html", null ],
    [ "SDL_GameControllerButtonBind", "structSDL__GameControllerButtonBind.html", null ],
    [ "SDL_HapticCondition", "structSDL__HapticCondition.html", null ],
    [ "SDL_HapticConstant", "structSDL__HapticConstant.html", null ],
    [ "SDL_HapticCustom", "structSDL__HapticCustom.html", null ],
    [ "SDL_HapticDirection", "structSDL__HapticDirection.html", null ],
    [ "SDL_HapticEffect", "unionSDL__HapticEffect.html", null ],
    [ "SDL_HapticLeftRight", "structSDL__HapticLeftRight.html", null ],
    [ "SDL_HapticPeriodic", "structSDL__HapticPeriodic.html", null ],
    [ "SDL_HapticRamp", "structSDL__HapticRamp.html", null ],
    [ "SDL_JoyAxisEvent", "structSDL__JoyAxisEvent.html", null ],
    [ "SDL_JoyBallEvent", "structSDL__JoyBallEvent.html", null ],
    [ "SDL_JoyButtonEvent", "structSDL__JoyButtonEvent.html", null ],
    [ "SDL_JoyDeviceEvent", "structSDL__JoyDeviceEvent.html", null ],
    [ "SDL_JoyHatEvent", "structSDL__JoyHatEvent.html", null ],
    [ "SDL_JoystickGUID", "structSDL__JoystickGUID.html", null ],
    [ "SDL_KeyboardEvent", "structSDL__KeyboardEvent.html", null ],
    [ "SDL_Keysym", "structSDL__Keysym.html", null ],
    [ "SDL_MessageBoxButtonData", "structSDL__MessageBoxButtonData.html", null ],
    [ "SDL_MessageBoxColor", "structSDL__MessageBoxColor.html", null ],
    [ "SDL_MessageBoxColorScheme", "structSDL__MessageBoxColorScheme.html", null ],
    [ "SDL_MessageBoxData", "structSDL__MessageBoxData.html", null ],
    [ "SDL_MouseButtonEvent", "structSDL__MouseButtonEvent.html", null ],
    [ "SDL_MouseMotionEvent", "structSDL__MouseMotionEvent.html", null ],
    [ "SDL_MouseWheelEvent", "structSDL__MouseWheelEvent.html", null ],
    [ "SDL_MultiGestureEvent", "structSDL__MultiGestureEvent.html", null ],
    [ "SDL_OSEvent", "structSDL__OSEvent.html", null ],
    [ "SDL_Palette", "structSDL__Palette.html", null ],
    [ "SDL_PixelFormat", "structSDL__PixelFormat.html", null ],
    [ "SDL_Point", "structSDL__Point.html", null ],
    [ "SDL_QuitEvent", "structSDL__QuitEvent.html", null ],
    [ "SDL_Rect", "structSDL__Rect.html", null ],
    [ "SDL_RendererInfo", "structSDL__RendererInfo.html", null ],
    [ "SDL_RWops", "structSDL__RWops.html", null ],
    [ "SDL_Surface", "structSDL__Surface.html", null ],
    [ "SDL_SysWMEvent", "structSDL__SysWMEvent.html", null ],
    [ "SDL_SysWMinfo", "structSDL__SysWMinfo.html", null ],
    [ "SDL_SysWMmsg", "structSDL__SysWMmsg.html", null ],
    [ "SDL_TextEditingEvent", "structSDL__TextEditingEvent.html", null ],
    [ "SDL_TextInputEvent", "structSDL__TextInputEvent.html", null ],
    [ "SDL_TouchFingerEvent", "structSDL__TouchFingerEvent.html", null ],
    [ "SDL_UserEvent", "structSDL__UserEvent.html", null ],
    [ "SDL_version", "structSDL__version.html", null ],
    [ "SDL_WindowEvent", "structSDL__WindowEvent.html", null ],
    [ "SDL_WindowShapeMode", "structSDL__WindowShapeMode.html", null ],
    [ "SDL_WindowShapeParams", "unionSDL__WindowShapeParams.html", null ],
    [ "SDLTest_CommonState", "structSDLTest__CommonState.html", null ],
    [ "SDLTest_Crc32Context", "structSDLTest__Crc32Context.html", null ],
    [ "SDLTest_Md5Context", "structSDLTest__Md5Context.html", null ],
    [ "SDLTest_RandomContext", "structSDLTest__RandomContext.html", null ],
    [ "SDLTest_SurfaceImage_s", "structSDLTest__SurfaceImage__s.html", null ],
    [ "SDLTest_TestCaseReference", "structSDLTest__TestCaseReference.html", null ],
    [ "SDLTest_TestSuiteReference", "structSDLTest__TestSuiteReference.html", null ],
    [ "servernetadr_t", "classservernetadr__t.html", null ],
    [ "Valve.Steamworks.servernetadr_t", "structValve_1_1Steamworks_1_1servernetadr__t.html", null ],
    [ "Valve.Steamworks.SetPersonaNameResponse_t", "structValve_1_1Steamworks_1_1SetPersonaNameResponse__t.html", null ],
    [ "SetPersonaNameResponse_t", "structSetPersonaNameResponse__t.html", null ],
    [ "SetUserItemVoteResult_t", "structSetUserItemVoteResult__t.html", null ],
    [ "Valve.Steamworks.SetUserItemVoteResult_t", "structValve_1_1Steamworks_1_1SetUserItemVoteResult__t.html", null ],
    [ "Valve.Steamworks.SocketStatusCallback_t", "structValve_1_1Steamworks_1_1SocketStatusCallback__t.html", null ],
    [ "SocketStatusCallback_t", "structSocketStatusCallback__t.html", null ],
    [ "Valve.Steamworks.SteamAPI", "classValve_1_1Steamworks_1_1SteamAPI.html", null ],
    [ "SteamAPICallCompleted_t", "structSteamAPICallCompleted__t.html", null ],
    [ "Valve.Steamworks.SteamAPICallCompleted_t", "structValve_1_1Steamworks_1_1SteamAPICallCompleted__t.html", null ],
    [ "Valve.Steamworks.SteamAPIInterop", "classValve_1_1Steamworks_1_1SteamAPIInterop.html", null ],
    [ "Valve.Steamworks.SteamAppInstalled_t", "structValve_1_1Steamworks_1_1SteamAppInstalled__t.html", null ],
    [ "Valve.Steamworks.SteamAppUninstalled_t", "structValve_1_1Steamworks_1_1SteamAppUninstalled__t.html", null ],
    [ "SteamCallback_t", "structSteamCallback__t.html", null ],
    [ "Valve.Steamworks.SteamControllerState001_t", "structValve_1_1Steamworks_1_1SteamControllerState001__t.html", null ],
    [ "SteamControllerState001_t", "structSteamControllerState001__t.html", null ],
    [ "Valve.Steamworks.SteamID_t", "structValve_1_1Steamworks_1_1SteamID__t.html", null ],
    [ "CSteamID::SteamID_t::SteamIDComponent_t", "structCSteamID_1_1SteamID__t_1_1SteamIDComponent__t.html", null ],
    [ "Valve.Steamworks.SteamIDComponent_t", "structValve_1_1Steamworks_1_1SteamIDComponent__t.html", null ],
    [ "SteamInventoryDefinitionUpdate_t", "structSteamInventoryDefinitionUpdate__t.html", null ],
    [ "SteamInventoryFullUpdate_t", "structSteamInventoryFullUpdate__t.html", null ],
    [ "Valve.Steamworks.SteamInventoryFullUpdate_t", "structValve_1_1Steamworks_1_1SteamInventoryFullUpdate__t.html", null ],
    [ "Valve.Steamworks.SteamInventoryResultReady_t", "structValve_1_1Steamworks_1_1SteamInventoryResultReady__t.html", null ],
    [ "SteamInventoryResultReady_t", "structSteamInventoryResultReady__t.html", null ],
    [ "Valve.Steamworks.SteamItemDetails_t", "structValve_1_1Steamworks_1_1SteamItemDetails__t.html", null ],
    [ "SteamItemDetails_t", "structSteamItemDetails__t.html", null ],
    [ "SteamParamStringArray_t", "structSteamParamStringArray__t.html", null ],
    [ "Valve.Steamworks.SteamParamStringArray_t", "structValve_1_1Steamworks_1_1SteamParamStringArray__t.html", null ],
    [ "SteamPS3Memory_t", "structSteamPS3Memory__t.html", null ],
    [ "SteamPS3Params_t", "structSteamPS3Params__t.html", null ],
    [ "SteamServerConnectFailure_t", "structSteamServerConnectFailure__t.html", null ],
    [ "Valve.Steamworks.SteamServerConnectFailure_t", "structValve_1_1Steamworks_1_1SteamServerConnectFailure__t.html", null ],
    [ "SteamServersConnected_t", "structSteamServersConnected__t.html", null ],
    [ "SteamServersDisconnected_t", "structSteamServersDisconnected__t.html", null ],
    [ "Valve.Steamworks.SteamServersDisconnected_t", "structValve_1_1Steamworks_1_1SteamServersDisconnected__t.html", null ],
    [ "SteamShutdown_t", "structSteamShutdown__t.html", null ],
    [ "SteamUGCDetails_t", "structSteamUGCDetails__t.html", null ],
    [ "Valve.Steamworks.SteamUGCDetails_t", "structValve_1_1Steamworks_1_1SteamUGCDetails__t.html", null ],
    [ "Valve.Steamworks.SteamUGCQueryCompleted_t", "structValve_1_1Steamworks_1_1SteamUGCQueryCompleted__t.html", null ],
    [ "SteamUGCQueryCompleted_t", "structSteamUGCQueryCompleted__t.html", null ],
    [ "Valve.Steamworks.SteamUGCRequestUGCDetailsResult_t", "structValve_1_1Steamworks_1_1SteamUGCRequestUGCDetailsResult__t.html", null ],
    [ "SteamUGCRequestUGCDetailsResult_t", "structSteamUGCRequestUGCDetailsResult__t.html", null ],
    [ "SteamUnifiedMessagesSendMethodResult_t", "structSteamUnifiedMessagesSendMethodResult__t.html", null ],
    [ "Valve.Steamworks.SteamUnifiedMessagesSendMethodResult_t", "structValve_1_1Steamworks_1_1SteamUnifiedMessagesSendMethodResult__t.html", null ],
    [ "StoreAuthURLResponse_t", "structStoreAuthURLResponse__t.html", null ],
    [ "Valve.Steamworks.StoreAuthURLResponse_t", "structValve_1_1Steamworks_1_1StoreAuthURLResponse__t.html", null ],
    [ "Valve.Steamworks.SubmitItemUpdateResult_t", "structValve_1_1Steamworks_1_1SubmitItemUpdateResult__t.html", null ],
    [ "SubmitItemUpdateResult_t", "structSubmitItemUpdateResult__t.html", null ],
    [ "UDPpacket", "structUDPpacket.html", null ],
    [ "Valve.Steamworks.UserAchievementIconFetched_t", "structValve_1_1Steamworks_1_1UserAchievementIconFetched__t.html", null ],
    [ "UserAchievementIconFetched_t", "structUserAchievementIconFetched__t.html", null ],
    [ "Valve.Steamworks.UserAchievementStored_t", "structValve_1_1Steamworks_1_1UserAchievementStored__t.html", null ],
    [ "UserAchievementStored_t", "structUserAchievementStored__t.html", null ],
    [ "UserFavoriteItemsListChanged_t", "structUserFavoriteItemsListChanged__t.html", null ],
    [ "Valve.Steamworks.UserFavoriteItemsListChanged_t", "structValve_1_1Steamworks_1_1UserFavoriteItemsListChanged__t.html", null ],
    [ "Valve.Steamworks.UserStatsReceived_t", "structValve_1_1Steamworks_1_1UserStatsReceived__t.html", null ],
    [ "UserStatsReceived_t", "structUserStatsReceived__t.html", null ],
    [ "Valve.Steamworks.UserStatsStored_t", "structValve_1_1Steamworks_1_1UserStatsStored__t.html", null ],
    [ "UserStatsStored_t", "structUserStatsStored__t.html", null ],
    [ "Valve.Steamworks.UserStatsUnloaded_t", "structValve_1_1Steamworks_1_1UserStatsUnloaded__t.html", null ],
    [ "UserStatsUnloaded_t", "structUserStatsUnloaded__t.html", null ],
    [ "Valve.Steamworks.ValidateAuthTicketResponse_t", "structValve_1_1Steamworks_1_1ValidateAuthTicketResponse__t.html", null ],
    [ "ValidateAuthTicketResponse_t", "structValidateAuthTicketResponse__t.html", null ],
    [ "Valve.Steamworks.ValvePackingSentinel_t", "structValve_1_1Steamworks_1_1ValvePackingSentinel__t.html", null ],
    [ "ValvePackingSentinel_t", "structValvePackingSentinel__t.html", null ],
    [ "Valve.Steamworks.VolumeHasChanged_t", "structValve_1_1Steamworks_1_1VolumeHasChanged__t.html", null ]
];